### ISSUE TITLE
This package Outdated!

### ISSUE THREAD

**Issue by lacesz-sh** [KaOS-Community-Packages/messengerfordesktop#2]
Hello Dear Packagers!

This package is obsolete! Please update this package. I need it!

Fresh version: v2.0.9

Link: https://github.com/aluxian/Messenger-for-Desktop/releases

Thank you very much!

Laszlo Espadas

**Comment by demmm** [comment]
KCP is maintained by the community, users like you.  KCP has no packagers since nothing in it is packaged, it just consists of scripts that make it possible for you to easily build.
See https://kaosx.us/docs/kcp for more, and anyone can help maintain any such script (PKGBUILD) in KCP, including you.

**Comment by lacesz-sh** [comment]
Hello Demmm! Messenger for Desktop upgraded! Thank you! 👍
